import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import ThemeToggle from '@/components/theme-toggle';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning={true}
    >
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='white'
          enableSystem
          disableTransitionOnChange
        >
          <div className='min-h-screen flex flex-col'>
            <div className='h-16 w-full bg-slate-300 border dark:bg-slate-600 border-slate-800 flex place-content-between items-center p-5'>
              <span className='text-2xl font-bold'>Awesome Form</span>
              <ThemeToggle />
            </div>
            <div className='flex pt-12 items-center justify-center'>
              {children}
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
